TCF Agent: Fixed: compilation errors when compiled as C++ on Windows. Added testing of binaries built with MS Windows C++ compiler.

diff --git a/bin/mcc b/bin/mcc
--- a/bin/mcc
+++ b/bin/mcc
@@ -104,15 +104,14 @@ cmdpos=0
 cflag=0
 gflag=0
 Oflag=0
+language=
 oval=
 
-while getopts co:D:I:gOp: name
+while getopts co:D:I:gOp:x: name
 do
     case $name in
     c)
         cmd[cmdpos]="/c"
-        cmdpos=`expr $cmdpos + 1`
-        cmd[cmdpos]="/TC"
         cmdpos=`expr $cmdpos + 1`
         cflag=1
         ;;
@@ -130,12 +129,15 @@ do
         cmdpos=`expr $cmdpos + 1`
         ;;
     I)
-        cmd[cmdpos]="/I`cygpath -w "$OPTARG"`"
+        cmd[cmdpos]="/I`cygpath -m "$OPTARG"`"
         cmdpos=`expr $cmdpos + 1`
         ;;
     p)
-        cmd[cmdpos]="/Fd`cygpath -w "$OPTARG"`"
+        cmd[cmdpos]="/Fd`cygpath -m "$OPTARG"`"
         cmdpos=`expr $cmdpos + 1`
+        ;;
+    x)
+        language="$OPTARG"
         ;;
     *)
         echo Invalid option $name
@@ -144,12 +146,23 @@ do
     esac
 done
 
+if [ $cflag != 0 ] ; then
+  if [ "$language" = "" -o "$language" = "c" ] ; then
+    cmd[cmdpos]="/TC"
+    cmdpos=`expr $cmdpos + 1`
+  elif [ "$language" = "c++" ] ; then
+    cmd[cmdpos]="/TP"
+    cmdpos=`expr $cmdpos + 1`
+  else
+    echo "Invalid value of -x"
+    exit 1
+  fi
+fi
+
 shift `expr $OPTIND - 1`
 
-if [ ! -z "$oval" ]
-then
-    if [ $cflag = 0 ]
-    then
+if [ ! -z "$oval" ] ; then
+    if [ $cflag = 0 ] ; then
         cmd[cmdpos]="/Fe$oval"
     else
         cmd[cmdpos]="/Fo$oval"
@@ -157,14 +170,12 @@ then
     cmdpos=`expr $cmdpos + 1`
 fi
 
-if [ $gflag = 1 ]
-then
+if [ $gflag = 1 ] ; then
     CFLAGS1="/D_DEBUG /Zi /MTd"
 else
     CFLAGS1="/DNDEBUG /GF /Gy /FD /MT"
 fi
-if [ $Oflag = 0 ]
-then
+if [ $Oflag = 0 ] ; then
     CFLAGS2="/Od"
 else
     CFLAGS2="/O2 /Ob1"
